# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository: templates
      type: git
      name: DevOps/DevOps

trigger:
- master

variables: 
  - group: env-variables
extends:
  template: application-pipelines/simple-container-pipeline-v2.yml@templates
  parameters:
     dockerEnvVarOptions: '-e VAR1=$(env-test) -e VAR2="$(env-test2)" -e password-variable'
     ACRConnection: 'DOCKERPOC2_ACR'
     libraryName: "Devops-Nodejs-POC - Dev"
     sshEndpoint: 'KKSVAIDOCKERDV2_SSH'
     containerPort: 8080
     environment: "francois-test-environment"
     projectSteps:  
      - bash: echo Test 
        displayName: project step one
      - bash: echo "Test 2"
        displayName: project step two
      

