# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  repositories:
  - repository: templates
    type: git
    name: 'Devops/Devops'
    ref: refs/heads/less-parameters

variables:
- group: 'DevopsPOC - Prod'

extends:
  template: application-pipelines/simple-container-pipeline-extends.yml@templates
  parameters:
    # Generic information
    containerRegistry: 'DOCKERPOC2_ACR'
    containerRegistryUrl: 'dockerpoc2.azurecr.io'
    imageName: mytodolistpoc

    # Build context
    buildImage: True
    buildSelfHostedAgent: False
    
    # Deployment context
    deploymentsList:
    - templateType: 'container-onprem-deploy'
      libraryName:  "Devops-Nodejs-POC - Dev"
      environmentName: 'Development'
      dependsOn: Build
      sshEndpoint: 'KKSVAIDOCKERDV2_SSH'
      containerPort: 8080
      exposedPort: 8080
      containerName: 'My-TodoList-POC'
      environmentsVariables:
        - Var1=Val1
        - Var2=Val1
        - Var3=Val1


      

