# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository: templates
      type: git
      name: DevOps/DevOps

trigger:
- master

variables: 
  - group: env-variables
extends:
  template: application-pipelines/simple-container-pipeline.yml@templates
  parameters:
     dockerEnvVarOptions: '-e VAR1=$(env-test) -e VAR2="$(env-test2)" -e password-variable'
     libraryName: "Devops-Nodejs-POC - Dev"
     azureSubscriptionEndpoint: 592636b8-b436-47ba-a3f6-3908bede0677
     azureContainerRegistry: '{"loginServer":"dockerpoc2.azurecr.io", "id" : "/subscriptions/4563b8b2-94cb-4c1e-a18e-29684fbf97ed/resourceGroups/DockerRG/providers/Microsoft.ContainerRegistry/registries/dockerpoc2"}'
     azureSubscription: GdemicheleCloud
     sshEndpoint: 'KKSVAIDOCKERDV2_SSH'
     containerPort: 8080
     environment: "francois-test-environment"
     projectSteps:  
      - bash: echo Test 
        displayName: project step one
      - bash: echo "Test 2"
        displayName: project step two
      

