resources:
  repositories:
    - repository: templates
      type: git
      name: DevOps/DevOps

trigger:
- prod


variables: 
  - group: env-variables
extends:
  template: application-pipelines/simple-container-pipeline.yml@templates
  parameters:
    ACRConnection: 'DOCKERPOC2_ACR'
    libraryName: "Devops-Nodejs-POC - Dev"
    environment: "francois-test-environment"
    dockerEnvVarOptions: '-e VAR1=$(env-test) -e VAR2="$(env-test2)" -e password-variable'
    sshEndpoint: 'KKSVAIDOCKERPD_SSH'
    containerPort: 8080