

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- prod

resources:
  repositories:
  - repository: templates
    type: git
    name: 'Devops/Devops'
    ref: refs/heads/less-parameters

variables:
- group: 'DevopsPOC - Prod'
- template: _boilerplate-templates/global/global-shared-variables.yml@templates

extends:
  template: application-pipelines/simple-container-pipeline-extends.yml@templates
  parameters:
    buildImage: False
    containerRegistry: $(gblAzureContainerRegistry)
    containerRegistryUrl: $(gblAzureContainerRegistryUrl)
    imageName: mytodolistpoc
    
    deploymentsList:
    - templateType: 'container-onprem-deploy'
      libraryName: 'Devops-Nodejs-POC - Dev'
      selfHostedAgent: True
      environmentName: "francois_test_environment"
      dependsOn: []
      sshEndpoint: $(gblSSHDigitalTwinProd)  
      containerPort: 8080
      exposedPort: 8080
      containerName: 'My-TodoList-POC'
      environmentsVariables:
        - Var1=Val1
        - Var2=Val1
        - Var3=Val1
      
