# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: yesNo # name of the parameter; required
  type: boolean # data type of the parameter; required
  default: false
- name: libraryName
  type: string
- name: azureSubscriptionEndpoint
  type: string
- name: azureContainerRegistry
  type: string
- name: azureSubscription
  type: string
- name: sshEndpoint 
  type: string


stages:
  - stage: JFF
    displayName: Just for fun
    jobs:
    - job: A
      steps:
      - script: echo ${{parameters.yesNo}}
  - stage: Build
    jobs:
      - job: Docker
        pool:
          vmImage: ubuntu-18.04    
        steps:
          - task: Docker@0
            displayName: Build an image
            inputs:
              azureSubscriptionEndpoint: ${{parameters.azureSubscriptionEndpoint}}
              azureContainerRegistry: ${{parameters.azureContainerRegistry}}
              action: Build an image
          - task: Docker@0
            displayName: Push an image to ARC
            inputs:
              azureSubscriptionEndpoint: ${{parameters.azureSubscriptionEndpoint}}
              azureContainerRegistry: ${{parameters.azureContainerRegistry}}
              action: Push an image
  - stage: DeployOnPremDev
    dependsOn: Build    # this stage runs after Build
    displayName: Deploy to on-prem Dev
    variables:
      - group: ${{parameters.libraryName}}
    jobs:
      - deployment: 
        pool:
          name: DevopsPOC
          demands:
            - agent.name -equals DevOps_Ubuntu_Kruger 
        environment: "francois-test-environment"  
        strategy:
          runOnce:
            deploy:
              steps:
                - task: Docker@0
                  displayName: 'Pull an Image from ARC'
                  inputs:
                    azureSubscription: ${{parameters.azureSubscription}}
                    azureContainerRegistry: ${{parameters.azureContainerRegistry}}
                    action: 'Run a Docker command'
                    customCommand: 'pull $(ARC)/$(ImageName):$(Build.BuildId)'
                - task: Docker@0
                  displayName: 'Save Image TAR to Agent Disk'
                  inputs:
                    action: 'Run a Docker command'
                    customCommand: 'save -o $(ARC)_$(ImageName)_$(Build.BuildId).tar $(ARC)/$(ImageName):$(Build.BuildId)'
                - task: Docker@0
                  displayName: 'Remove Image by Force from Agent Registry'
                  inputs:
                    action: 'Run a Docker command'
                    customCommand: 'image rm --force $(ARC)_$(ImageName)_$(Build.BuildId).tar $(ARC)/$(ImageName):$(Build.BuildId)'
                - task: CopyFilesOverSSH@0
                  displayName: 'Copy Image TAR to Remote Server'
                  inputs:
                    sshEndpoint: ${{parameters.sshEndpoint}}
                    contents: '$(ARC)_$(ImageName)_$(Build.BuildId).tar'
                - task: DeleteFiles@1
                  displayName: 'Delete Image TAR from Agent Disk'
                  inputs:
                    SourceFolder: '$(build.artifactstagingdirectory)'
                    Contents: '$(ARC)_$(ImageName)_$(Build.BuildId).tar'
                - task: SSH@0
                  displayName: 'Load Image TAR to Remote Server Registry'
                  inputs:
                    sshEndpoint: ${{parameters.sshEndpoint}}
                    commands: 'docker load -i $(ARC)_$(ImageName)_$(Build.BuildId).tar'
                - task: SSH@0
                  displayName: 'Remove Container by Force on Remote Server'
                  continueOnError: true
                  inputs:
                    sshEndpoint: ${{parameters.sshEndpoint}}
                    commands: 'docker rm --force $(ContainerName)'
                - task: SSH@0
                  displayName: 'Run Image on Remote Server'
                  inputs:
                    sshEndpoint: ${{parameters.sshEndpoint}}
                    commands: 'docker run --name $(ContainerName) -dp $(WebsitesPort):8080 $(ARC)/$(ImageName):$(Build.BuildId)'
                - task: SSH@0
                  displayName: 'Delete Image TAR on Remote Server Disk'
                  inputs:
                    sshEndpoint: ${{parameters.sshEndpoint}}
                    commands: 'rm $(ARC)_$(ImageName)_$(Build.BuildId).tar'                
  - stage: DeployAzureDev
    dependsOn: Build    # this stage runs after Build
    displayName: Deploy to Azure Dev
    variables:
      - group: "Devops-Nodejs-POC - Dev"
    jobs:
      - deployment: 
        pool:
          vmImage: ubuntu-18.04 
        environment: "Azure-Dev"  
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureRmWebAppDeployment@3
                  displayName: 'Azure App Service Deploy'
                  inputs:
                    azureSubscription: ${{parameters.azureSubscription}}
                    appType: applinux
                    WebAppName: '$(ContainerName)'
                    DockerNamespace: '$(ARC)'
                    DockerRepository: '$(ImageName)'
                    DockerImageTag: '$(BUILD.BUILDID)'
                    AppSettings: '-DOCKER_REGISTRY_SERVER_PASSWORD $(ARCPassword) -DOCKER_REGISTRY_SERVER_USERNAME $(ARCUsername) -PORT $(WebsitesPort)'
                    TakeAppOfflineFlag: true


  